### ISSUE TITLE
Timeout is too large

### ISSUE THREAD

**Issue by mingguichen** [simonsfoundation/CaImAn#114]
Hi, thanks for the great software. 

When I ran the demo "demo_caiman_cnmf", I got the following error from cnmf.spatial.update_spatial_components:

Initializing update of Spatial Components
computing the distance indicators
found spatial support for each component
memmaping
Updating Spatial Components using lasso lars
thresholding components
---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
C:\Program Files\Anaconda3\envs\atlab-pipeline\lib\site-packages\ipyparallel\client\asyncresult.py in _ordered_iter(self)
    691         try:
--> 692             rlist = self.get(0)
    693         except error.TimeoutError:

C:\Program Files\Anaconda3\envs\atlab-pipeline\lib\site-packages\ipyparallel\client\asyncresult.py in get(self, timeout)
    168         else:
--> 169             raise error.TimeoutError("Result not ready.")
    170 

TimeoutError: Result not ready.

During handling of the above exception, another exception occurred:

OverflowError                             Traceback (most recent call last)
<ipython-input-12-9c06a9aeec46> in <module>()
----> 1 A,b,Cin,f_in = cnmf.spatial.update_spatial_components(Yr, Cin, f_in, Ain, sn=sn, dview=dview,**options['spatial_params'])

D:\Research\Programs\Included\ATLab\CaImAn\caiman\source_extraction\cnmf\spatial.py in update_spatial_components(Y, C, f, A_in, sn, dims, min_size, max_size, dist, normalize_yyt_one, method, expandCore, dview, n_pixels_per_process, medw, thr_method, maxthr, nrgthr, extract_cc, b_in, se, ss, nb, method_ls, update_background_components, low_rank_background)
    218     print("thresholding components")
    219     A_ = threshold_components(A_, dims, dview=dview, medw=medw, thr_method=thr_method,
--> 220                               maxthr=maxthr, nrgthr=nrgthr, extract_cc=extract_cc, se=se, ss=ss)
    221 
    222     ff = np.where(np.sum(A_, axis=0) == 0)  # remove empty components

D:\Research\Programs\Included\ATLab\CaImAn\caiman\source_extraction\cnmf\spatial.py in threshold_components(A, dims, medw, thr_method, maxthr, nrgthr, extract_cc, se, ss, dview)
    647         res = list(map(threshold_components_parallel, pars))
    648 
--> 649     for r in res:
    650         At, i = r
    651         Ath[:, i] = At

C:\Program Files\Anaconda3\envs\atlab-pipeline\lib\site-packages\ipyparallel\client\asyncresult.py in __iter__(self)
    671     def __iter__(self):
    672         it = self._ordered_iter if self.ordered else self._unordered_iter
--> 673         for r in it():
    674             yield r
    675 

C:\Program Files\Anaconda3\envs\atlab-pipeline\lib\site-packages\ipyparallel\client\asyncresult.py in _ordered_iter(self)
    695             evt = Event()
    696             for child in self._children:
--> 697                 self._wait_for_child(child, evt=evt)
    698                 for r in self._yield_child_results(child):
    699                     yield r

C:\Program Files\Anaconda3\envs\atlab-pipeline\lib\site-packages\ipyparallel\client\asyncresult.py in _wait_for_child(child, evt, timeout)
    375         evt.clear()
    376         child.add_done_callback(lambda f: evt.set())
--> 377         evt.wait(timeout)
    378 
    379     # asynchronous iterator:

C:\Program Files\Anaconda3\envs\atlab-pipeline\lib\threading.py in wait(self, timeout)
    547             signaled = self._flag
    548             if not signaled:
--> 549                 signaled = self._cond.wait(timeout)
    550             return signaled
    551 

C:\Program Files\Anaconda3\envs\atlab-pipeline\lib\threading.py in wait(self, timeout)
    295             else:
    296                 if timeout > 0:
--> 297                     gotit = waiter.acquire(True, timeout)
    298                 else:
    299                     gotit = waiter.acquire(False)

OverflowError: timeout value is too large

Do you know what the problem is? I l already searched online and asked around. Thanks.

**Comment by agiovann** [comment]
Hello, what version of Python and which OS are you using. We know for a fact that there is a an issue with Python 3 and Mac OS X

**Comment by mingguichen** [comment]
Thanks, Andrea! It's python 3.5 under windows 10.

**Comment by agiovann** [comment]
Thank you! Would you mind trying with Python 2.7?

**Comment by mingguichen** [comment]
Thanks, Andrea. I tried to install caiman in a clean Windows, and it worked in Jupiter. Do you know how to import caiman in spyder? I just finished the steps you provided. I tried Ubuntu, it works fine. But I am a little bit greedy and still want to work Windows out. Thanks.

**Comment by agiovann** [comment]
I guess you figured it out. Caiman in spyder is the usual way "import caiman as cm"

**Comment by mingguichen** [comment]
Thanks, Andrea! I could run the entire caiman under windows 10 now. Thanks!

**Comment by epnev** [comment]
@mingguichen Did you do anything different compared to what our instructions say, to install caiman on windows? If so, can you tell us so we update them?

**Comment by mingguichen** [comment]
Thanks for the message. I follow the same instruction you guys posted under WIndows 10. Thanks for that! Then, I got an error saying "Hub connection timed out" from cluster.py. Finally, I replaced its start_server function with the following code. Everything works now, except the SLURM. Thanks!

def start_server(slurm_script=None, ipcluster="ipcluster", ncpus = None):
    """
    programmatically start the ipyparallel server

    Parameters:
    ----------
    ncpus: int
        number of processors

    ipcluster : str
        ipcluster binary file name; requires 4 path separators on Windows. ipcluster="C:\\\\Anaconda2\\\\Scripts\\\\ipcluster.exe"
         Default: "ipcluster"
    """
    sys.stdout.write("Starting cluster...")
    sys.stdout.flush()
    if ncpus is None:
        ncpus=psutil.cpu_count()

    def GetIpyParallelClient():
        while True:
            try:
                client = ipyparallel.Client()
                break
            except:
                pass
        return client

    if slurm_script is None:
        if ipcluster == "ipcluster":
            subprocess.Popen("ipcluster start -n {0}".format(ncpus), shell=True, close_fds=(os.name != 'nt'))
        else:
            subprocess.Popen(shlex.split("{0} start -n {1}".format(ipcluster, ncpus)), shell=True, close_fds=(os.name != 'nt'))

        # Check that all processes have started
        client = GetIpyParallelClient()
                
        while len(client) < ncpus:
            sys.stdout.write(".")
            sys.stdout.flush()
            client.close()
            client = GetIpyParallelClient()
            
        client.close()

    else:
        shell_source(slurm_script)
        pdir, profile = os.environ['IPPPDIR'], os.environ['IPPPROFILE']
        c = Client(ipython_dir=pdir, profile=profile)
        ee = c[:]
        ne = len(ee)
        print(('Running on %d engines.' % (ne)))
        c.close()
        sys.stdout.write(" done\n")

**Comment by mingguichen** [comment]
Thanks for the message. I follow the same instruction you guys posted under
WIndows 10. Thanks for that! Then, I got an error saying "Hub connection
timed out" from cluster.py. Finally, I replaced its start_server function
with the following code. Everything works now, except the SLURM. Thanks!

def start_server(slurm_script=None, ipcluster="ipcluster", ncpus = None):
    """
    programmatically start the ipyparallel server

    Parameters:
    ----------
    ncpus: int
        number of processors

    ipcluster : str
        ipcluster binary file name; requires 4 path separators on Windows.
ipcluster="C:\\\\Anaconda2\\\\Scripts\\\\ipcluster.exe"
         Default: "ipcluster"
    """
    sys.stdout.write("Starting cluster...")
    sys.stdout.flush()
    if ncpus is None:
        ncpus=psutil.cpu_count()

*    def GetIpyParallelClient():*
*        while True:*
*            try:*
*                client = ipyparallel.Client()*
*                break*
*            except:*
*                pass*
*        return client*

    if slurm_script is None:
        if ipcluster == "ipcluster":
            subprocess.Popen("ipcluster start -n {0}".format(ncpus),
shell=True, close_fds=(os.name != 'nt'))
        else:
            subprocess.Popen(shlex.split("{0} start -n
{1}".format(ipcluster, ncpus)), shell=True, close_fds=(os.name != 'nt'))

        # Check that all processes have started
       * client = GetIpyParallelClient()*

        while len(client) < ncpus:
            sys.stdout.write(".")
            sys.stdout.flush()
            client.close()
            *client = GetIpyParallelClient()*

        client.close()

    else:
        shell_source(slurm_script)
        pdir, profile = os.environ['IPPPDIR'], os.environ['IPPPROFILE']
        c = Client(ipython_dir=pdir, profile=profile)
        ee = c[:]
        ne = len(ee)
        print(('Running on %d engines.' % (ne)))
        c.close()
        sys.stdout.write(" done\n")

**Comment by cortadita** [comment]
Hi @mingguichen, could I ask you how you installed caiman with python 2.7 on windows? I am currently running into the same timeout issue; and I gave up on python 2 earlier when I realised there is no easy way of installing tensorflow on it. How did you get around that issue?

**Comment by agiovann** [comment]
Would you like to create a pull request? Otherwise I can proceed myself to
add the changes. It is just to give you credit. Let me know what works best
for you!

**Comment by mingguichen** [comment]
Hi Andrea, I already modified my code in terms of python naming conventions. Please see the pull request now. I followed the "Installation on windows" guideline on the webpage, with Spyder and jupyter notebook in Python 3.5.4 running normally now. It should be noted that my os is windows server 2016, but the kernel is still windows 10, as indicated by version number and Microsoft official explanation. Hope this could help the windows forks, making CaImAn even more popular. Thanks and cheers:-)

**Comment by mingguichen** [comment]
Hi @cortadita , I never tried python 2.7 for tensorflow, as it's not supported officially from google for python 2.7. I followed the "Installation on windows" guideline on the webpage, with Spyder and jupyter notebook in Python 3.5.4 running normally now. It should be noted that my os is windows server 2016, but the kernel is still windows 10, as indicated by version number and Microsoft official explanation. Hope it helps!

**Comment by cortadita** [comment]
@mingguichen Oh sorry - I think I misunderstood the conversation. Thanks for clarifying!
