### ISSUE TITLE
demo_caiman_cnmf.ipynb evaluate_components error

### ISSUE THREAD

**Issue by Yassum** [simonsfoundation/CaImAn#49]
In the 19th cell it states ```fitness_raw, fitness_delta, erfc_raw, erfc_delta, r_values, significant_samples = evaluate_components(Y, traces, A2, C2, b2, f2, remove_baseline=True, N=5, robust_std=False, Athresh = 0.1, Npeaks = Npeaks, tB=tB, tA = tA, thresh_C = 0.3)```

I think it should read 
```fitness_raw, fitness_delta, erfc_raw, erfc_delta, r_values, significant_samples = evaluate_components(Y, traces, A2, C2, b2, f2, final_frate=final_frate, remove_baseline=True, N=5, robust_std=False, Athresh = 0.1, Npeaks = Npeaks, thresh_C = 0.3)```

**Comment by agiovann** [comment]
Thank you Yassum for the heads up. I will fix it.
