### ISSUE TITLE
Little bug when creating memap

### ISSUE THREAD

**Issue by Danieldemalmazet** [simonsfoundation/CaImAn#51]
Hi Andrea Giovannucci,
My name is Daniel de Malmazet. I'm a PhD student at NERF, Leuven - Belgium. I work with Calcium Imaging and I am using your code. Thank you for sharing it. It's great and very usefull!
I've noted a small bug in the function save_memmap_each (line 109 of file mmaping.py). I would suggest instead of: base_name+str(idx), to write instead: base_name+'{:04d}'.format(idx) . The reason is that after this function is called in the main code, you do: name_new.sort(). The problem is if you have the data contained in more than 10 tiff files, then you'll have a mismatch because the order will be the following: _1,_10,_11,.._19,_2,_20,_21,...,_3.. and so on.

I have also another issue with very large data set (e.g. 1024x1024x70000). I am using a 256gb RAM system and I am performing a multipatch analysis in order to segment the data, but I have memory issues. I was wondering what is the size of the dataset you usually analyse with this program and if you could give me any indication.

I was looking for your contact information but I couldn't find it. Please contact me by email if possible at daniel.demalmazet@nerf.be 

Best
Daniel

**Comment by agiovann** [comment]
This issue depends on naming conventions. Ram memory, hopefully fixed?
