### ISSUE TITLE
Please honor scikit-image license

### ISSUE THREAD

**Issue by stefanv** [simonsfoundation/CaImAn#67]
Dear team,

I've noticed that you include some of the scikit-image source in your package.  We are very happy to see that you find our code useful!

Our code is released under the modified BSD license, which allows you to use it freely and without restriction, as long as you include a copy of our license: https://github.com/scikit-image/scikit-image/blob/master/LICENSE.txt

I happened to notice, because I was reading your source, hoping to use your package in the future :)

Best regards
Stéfan

**Comment by agiovann** [comment]
Dear @stefanv, please excuse the mistake. We have added the licensing information but please double check to make sure I did not miss anything. FYI, I also accidentally omitted to acknowledge the fact that the source was originally coming from SIMA, so I added also that reference now. 

Best

**Comment by stefanv** [comment]
Thanks, @agiovann!  You can mention the license in one place, and have it apply to multiple functions (I left a comment on your commit to that effect).  But otherwise looks great.
