### ISSUE TITLE
setup.py can't find source_extraction/cnmf/oasis.pyx

### ISSUE THREAD

**Issue by dgoodwin208** [simonsfoundation/CaImAn#70]
I see this when I run the last step of the installation instructions. 

```
python setup.py build_ext -i
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    ext_modules=cythonize("caiman/source_extraction/cnmf/oasis.pyx")
  File "/Users/Goody/anaconda/envs/CaImAn/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 818, in cythonize
    aliases=aliases)
  File "/Users/Goody/anaconda/envs/CaImAn/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 704, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/Users/Goody/anaconda/envs/CaImAn/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 108, in nonempty
    raise ValueError(error_msg)
ValueError: 'caiman/source_extraction/cnmf/oasis.pyx' doesn't match any files
```

**Comment by j-friedrich** [comment]
Daniel, are you in the correct directory (CaImAn) when running `python setup.py build_ext -i`?

**Comment by dgoodwin208** [comment]
I'm in the Caiman git root directory

**Comment by dgoodwin208** [comment]
Thanks for the instant replies btw!

**Comment by dgoodwin208** [comment]
I think whatever went wrong with my fresh install (btw - this is my third clean install attempt. In the last try the qt5 plots were crashing every time >.<)

When I try to run the demos python is just not seeing caiman at all. It looks like somehow I'm not getting any of the caiman source code from the installation instructions .... I'm hoping this is a very silly issue to be resolved shortly

**Comment by dgoodwin208** [comment]
Ok - it seems that for a short period of time the folder 'caiman' was not in the repo? Seems just like bummer tiiming. Just saw @j-friedrich commit

**Comment by dgoodwin208** [comment]
Ok, it's all fine now. Somehow I didn't get the caiman folder in the clean git pull. I have no idea what happened, just moving on with life ;) sorry to bother you guys, setup.py works fine now
