### ISSUE TITLE
opencv does not work on OS X w/ default python3.6

### ISSUE THREAD

**Issue by bafonso** [simonsfoundation/CaImAn#81]
on OS X, If you install miniconda3.6 (default download for python 3.x) then when you issue 

`conda create -n CaImAn ipython --file requirements_conda.txt  `

it will not work when you reach opencv install. I suggest recommending to use 

`conda create -n CaImAn python=2.7 ipython --file requirements_conda.txt  ` 

or

`conda create -n CaImAn python=3.5 ipython --file requirements_conda.txt  ` (untested)

It will then install everything. I've also noticed missing bokeh from requirements_conda.txt

**Comment by agiovann** [comment]
Thank you Bruno! Solved, I updated the installation instructions.
