### ISSUE TITLE
FFT error 

### ISSUE THREAD

**Issue by agiovann** [simonsfoundation/CaImAn#83]
Hi @agiovann I've recently started to encounter a bug during the preprocessing of data. When get_noise_fft is called, there is a bug at the end with sn = mean_psd(psdx[ind], method = noise_method) I get an IndexError: boolean index did not match indexed array along dimension 2; dimension is 1537 but corresponding boolean dimension is 1538. Any idea what would cause this I'm trying to see where it goes wrong
it seems like there is an issue with the max_num_samples_fft, some combinations work and others not. I don't know if it's linked to the length of the movies (mine were 7500 frames), but I'll try playing around with it. As far as I can see, in my case (7500 frames), it works with 504, but not 500-503, 606, but not 604 or 605. Must be some kind of issues in the reshape in get_noise_fft

**Comment by colby-j-wise** [comment]
@agiovann Hi, getting same error. Have included stack trace in case it helps:

`(30, 30)
Something went wrong
You may think that it went well but reality is harsh
[0:apply]: 
IndexErrorTraceback (most recent call last)<string> in <module>()
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/map_reduce.pyc in cnmf_patches(args_in)
    131                 remove_very_bad_comps = options['patch_params']['remove_very_bad_comps'])
    132 
--> 133         cnm = cnm.fit(images)
    134         return idx_,shapes,scipy.sparse.coo_matrix(cnm.A),\
    135                cnm.b,cnm.C,cnm.f,cnm.S,cnm.bl,cnm.c1,\
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/cnmf.pyc in fit(self, images)
    255         if self.rf is None:  # no patches
    256             print('preprocessing ...')
--> 257             Yr, sn, g, psx = preprocess_data(Yr, dview=self.dview, **options['preprocess_params'])
    258 
    259             if self.Ain is None:
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in preprocess_data(Y, sn, dview, n_pixels_per_process, noise_range, noise_method, compute_g, p, lags, include_noise, pixels, max_num_samples_fft, check_nan)
    532 
    533     if sn is None:
--> 534         sn,psx=get_noise_fft_parallel(Y,n_pixels_per_process=n_pixels_per_process, dview = dview, noise_range = noise_range, noise_method = noise_method,max_num_samples_fft=max_num_samples_fft)
    535     else:
    536         psx=None
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in get_noise_fft_parallel(Y, n_pixels_per_process, dview, **kwargs)
    214     if dview is None:
    215         print('Single Thread')
--> 216         results = list(map(fft_psd_multithreading, argsin))
    217 
    218     else:
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in fft_psd_multithreading(args)
    324     idxs=list(range(i,i+num_pixels))
    325     print(len(idxs))
--> 326     res,psx=get_noise_fft(Y[idxs], **kwargs)
    327 
    328     return (idxs,res,psx)
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in get_noise_fft(Y, noise_range, noise_method, max_num_samples_fft)
    152         psdx = (old_div(1.,T))*abs(xdft)**2
    153         psdx[...,1:] *= 2
--> 154         sn = mean_psd(psdx[...,ind], method = noise_method)
    155 
    156     else:
IndexError: boolean index did not match indexed array along dimension 1; dimension is 1537 but corresponding boolean dimension is 1538

[1:apply]: 
IndexErrorTraceback (most recent call last)<string> in <module>()
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/map_reduce.pyc in cnmf_patches(args_in)
    131                 remove_very_bad_comps = options['patch_params']['remove_very_bad_comps'])
    132 
--> 133         cnm = cnm.fit(images)
    134         return idx_,shapes,scipy.sparse.coo_matrix(cnm.A),\
    135                cnm.b,cnm.C,cnm.f,cnm.S,cnm.bl,cnm.c1,\
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/cnmf.pyc in fit(self, images)
    255         if self.rf is None:  # no patches
    256             print('preprocessing ...')
--> 257             Yr, sn, g, psx = preprocess_data(Yr, dview=self.dview, **options['preprocess_params'])
    258 
    259             if self.Ain is None:
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in preprocess_data(Y, sn, dview, n_pixels_per_process, noise_range, noise_method, compute_g, p, lags, include_noise, pixels, max_num_samples_fft, check_nan)
    532 
    533     if sn is None:
--> 534         sn,psx=get_noise_fft_parallel(Y,n_pixels_per_process=n_pixels_per_process, dview = dview, noise_range = noise_range, noise_method = noise_method,max_num_samples_fft=max_num_samples_fft)
    535     else:
    536         psx=None
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in get_noise_fft_parallel(Y, n_pixels_per_process, dview, **kwargs)
    214     if dview is None:
    215         print('Single Thread')
--> 216         results = list(map(fft_psd_multithreading, argsin))
    217 
    218     else:
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in fft_psd_multithreading(args)
    324     idxs=list(range(i,i+num_pixels))
    325     print(len(idxs))
--> 326     res,psx=get_noise_fft(Y[idxs], **kwargs)
    327 
    328     return (idxs,res,psx)
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in get_noise_fft(Y, noise_range, noise_method, max_num_samples_fft)
    152         psdx = (old_div(1.,T))*abs(xdft)**2
    153         psdx[...,1:] *= 2
--> 154         sn = mean_psd(psdx[...,ind], method = noise_method)
    155 
    156     else:
IndexError: boolean index did not match indexed array along dimension 1; dimension is 1537 but corresponding boolean dimension is 1538

[2:apply]: 
IndexErrorTraceback (most recent call last)<string> in <module>()
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/map_reduce.pyc in cnmf_patches(args_in)
    131                 remove_very_bad_comps = options['patch_params']['remove_very_bad_comps'])
    132 
--> 133         cnm = cnm.fit(images)
    134         return idx_,shapes,scipy.sparse.coo_matrix(cnm.A),\
    135                cnm.b,cnm.C,cnm.f,cnm.S,cnm.bl,cnm.c1,\
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/cnmf.pyc in fit(self, images)
    255         if self.rf is None:  # no patches
    256             print('preprocessing ...')
--> 257             Yr, sn, g, psx = preprocess_data(Yr, dview=self.dview, **options['preprocess_params'])
    258 
    259             if self.Ain is None:
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in preprocess_data(Y, sn, dview, n_pixels_per_process, noise_range, noise_method, compute_g, p, lags, include_noise, pixels, max_num_samples_fft, check_nan)
    532 
    533     if sn is None:
--> 534         sn,psx=get_noise_fft_parallel(Y,n_pixels_per_process=n_pixels_per_process, dview = dview, noise_range = noise_range, noise_method = noise_method,max_num_samples_fft=max_num_samples_fft)
    535     else:
    536         psx=None
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in get_noise_fft_parallel(Y, n_pixels_per_process, dview, **kwargs)
    214     if dview is None:
    215         print('Single Thread')
--> 216         results = list(map(fft_psd_multithreading, argsin))
    217 
    218     else:
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in fft_psd_multithreading(args)
    324     idxs=list(range(i,i+num_pixels))
    325     print(len(idxs))
--> 326     res,psx=get_noise_fft(Y[idxs], **kwargs)
    327 
    328     return (idxs,res,psx)
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in get_noise_fft(Y, noise_range, noise_method, max_num_samples_fft)
    152         psdx = (old_div(1.,T))*abs(xdft)**2
    153         psdx[...,1:] *= 2
--> 154         sn = mean_psd(psdx[...,ind], method = noise_method)
    155 
    156     else:
IndexError: boolean index did not match indexed array along dimension 1; dimension is 1537 but corresponding boolean dimension is 1538

[3:apply]: 
IndexErrorTraceback (most recent call last)<string> in <module>()
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/map_reduce.pyc in cnmf_patches(args_in)
    131                 remove_very_bad_comps = options['patch_params']['remove_very_bad_comps'])
    132 
--> 133         cnm = cnm.fit(images)
    134         return idx_,shapes,scipy.sparse.coo_matrix(cnm.A),\
    135                cnm.b,cnm.C,cnm.f,cnm.S,cnm.bl,cnm.c1,\
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/cnmf.pyc in fit(self, images)
    255         if self.rf is None:  # no patches
    256             print('preprocessing ...')
--> 257             Yr, sn, g, psx = preprocess_data(Yr, dview=self.dview, **options['preprocess_params'])
    258 
    259             if self.Ain is None:
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in preprocess_data(Y, sn, dview, n_pixels_per_process, noise_range, noise_method, compute_g, p, lags, include_noise, pixels, max_num_samples_fft, check_nan)
    532 
    533     if sn is None:
--> 534         sn,psx=get_noise_fft_parallel(Y,n_pixels_per_process=n_pixels_per_process, dview = dview, noise_range = noise_range, noise_method = noise_method,max_num_samples_fft=max_num_samples_fft)
    535     else:
    536         psx=None
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in get_noise_fft_parallel(Y, n_pixels_per_process, dview, **kwargs)
    214     if dview is None:
    215         print('Single Thread')
--> 216         results = list(map(fft_psd_multithreading, argsin))
    217 
    218     else:
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in fft_psd_multithreading(args)
    324     idxs=list(range(i,i+num_pixels))
    325     print(len(idxs))
--> 326     res,psx=get_noise_fft(Y[idxs], **kwargs)
    327 
    328     return (idxs,res,psx)
/Users/johnsenh/Desktop/Colby_Research/CaImAn/caiman/source_extraction/cnmf/pre_processing.pyc in get_noise_fft(Y, noise_range, noise_method, max_num_samples_fft)
    152         psdx = (old_div(1.,T))*abs(xdft)**2
    153         psdx[...,1:] *= 2
--> 154         sn = mean_psd(psdx[...,ind], method = noise_method)
    155 
    156     else:
IndexError: boolean index did not match indexed array along dimension 1; dimension is 1537 but corresponding boolean dimension is 1538

4 more exceptions ...`

**Comment by agiovann** [comment]
Dear @colby-j-wise,

would you let me know if things work out now?

Thank you!

**Comment by sriramrn** [comment]
Dear @agiovann ,

  I was facing this issue with my data that was 157 frames long but it was fine when I cropped it to 156 frames. After the update it works fine with the full data set. I haven't tried other sizes though.
