### ISSUE TITLE
where is environment.yml

### ISSUE THREAD

**Issue by zhuangjun1981** [simonsfoundation/CaImAn#96]
I am following the installing instruction in the README. But I am getting the following error after trying to create the environment. I guess it is because conda cannot find the enviornment.yml file since it does not exist in the repo root folder? Could anyone help me with this? Thanks. 

```
Using Anaconda API: https://api.anaconda.org

SpecNotFound: Invalid name, try the format: user/package
```
Jun

**Comment by zhuangjun1981** [comment]
I found it in the caiman1.0 branch. I assume it will be merged into master soon.

**Comment by epnev** [comment]
It's part of a different branch to be merged very soon into the master. Sorry for the confusion.

**Comment by epnev** [comment]
exactly.
