### ISSUE TITLE
setup.py doesn't specify subpackages

### ISSUE THREAD

**Issue by joe311** [simonsfoundation/CaImAn#99]
The current setup.py only specifies the top level caiman package - meaning when the package is built, in \lib...\caimain, only the source_extraction folder and top level .py files are included (base etc are missing), so that "python setup.py install" doesn't install a usable package on the system.  
If this isn't the desired behavior, let me know here and I'll send a pull request to fix setup.py to include the subpackages.

**Comment by agiovann** [comment]
Thank you Joe. Please go on with pull request.

Best

Andrea
